blank_issues_enabled: false
contact_links:
  - name: RevaLink zkEVM Docs
    url: https://bridge.revalink.network/
    about: Official RevaLink zkEVM Documentation
  - name: Telegram Group
    url: https://bridge.revalink.network/
    about: Official RevaLink zkEVM Telegram Group
  - name: Discord Community
    url: https://bridge.revalink.network/
    about: Official RevaLink zkEVM Discord Community
